/// This is autogenerated code. If you wish to edit this file press Scene Names -> Save scene names in options. 
namespace Homebrew
{
public enum Scenes
{
sceneTest = 0,
sceneKernel = 1,
sceneUI = 2,
Cross = 3,
sceneCross = 4
}
public static class ExtScenes	{	public static void To(this Scenes s)	{	ProcessingSceneLoad.To((int) s);	}}}
